// src/lib/formula-library.ts

export type FormulaSubject = "matematika" | "fisika" | "kimia" | "biologi";

export type FormulaVariable = {
  sym: string;
  meaning: string;
};

export type Formula = {
  id: string;
  name: string;
  latex: string;              // tanpa $ — dirender sebagai blok
  description: string;
  subject: FormulaSubject;
  topic: string;
  variables?: FormulaVariable[];
  tips?: string;
  tags?: string[];
};

export const FORMULA_SUBJECTS: { id: FormulaSubject; label: string; short: string }[] = [
  { id: "matematika", label: "Matematika", short: "MTK" },
  { id: "fisika", label: "Fisika", short: "FIS" },
  { id: "kimia", label: "Kimia", short: "KIM" },
  { id: "biologi", label: "Biologi", short: "BIO" },
];

export const FORMULA_LIBRARY: Formula[] = [
  /* ============================ MATEMATIKA ============================ */
  {
    id: "mtk-abc",
    name: "Rumus ABC (Kuadrat)",
    latex: "x_{1,2} = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
    description: "Akar-akar persamaan kuadrat ax² + bx + c = 0.",
    subject: "matematika",
    topic: "Persamaan Kuadrat",
    variables: [
      { sym: "a,b,c", meaning: "koefisien dengan a ≠ 0" },
      { sym: "x", meaning: "variabel" },
    ],
    tips: "Wajib cek diskriminan dulu. D < 0 → tidak ada akar real.",
    tags: ["kuadrat", "abc", "akar"],
  },
  {
    id: "mtk-diskriminan",
    name: "Diskriminan",
    latex: "D = b^2 - 4ac",
    description: "Menentukan jenis akar persamaan kuadrat.",
    subject: "matematika",
    topic: "Persamaan Kuadrat",
    tips: "D > 0 (2 akar real beda) · D = 0 (kembar) · D < 0 (imajiner).",
    tags: ["diskriminan", "kuadrat"],
  },
  {
    id: "mtk-jumlah-akar",
    name: "Jumlah & Hasil Kali Akar",
    latex: "x_1 + x_2 = -\\frac{b}{a}, \\quad x_1 x_2 = \\frac{c}{a}",
    description: "Hubungan akar persamaan kuadrat tanpa mencari akarnya.",
    subject: "matematika",
    topic: "Persamaan Kuadrat",
    tags: ["vieta", "akar", "kuadrat"],
  },
  {
    id: "mtk-kuadrat-binomial",
    name: "Kuadrat Binomial",
    latex: "(a+b)^2 = a^2 + 2ab + b^2, \\quad (a-b)^2 = a^2 - 2ab + b^2",
    description: "Ekspansi bentuk kuadrat dua suku.",
    subject: "matematika",
    topic: "Aljabar",
    tips: "Ingat suku tengah 2ab — jangan lupa faktornya 2.",
    tags: ["aljabar", "binomial"],
  },
  {
    id: "mtk-selisih-kuadrat",
    name: "Selisih Kuadrat",
    latex: "a^2 - b^2 = (a-b)(a+b)",
    description: "Faktorisasi cepat bentuk selisih dua kuadrat.",
    subject: "matematika",
    topic: "Aljabar",
    tags: ["faktorisasi", "aljabar"],
  },
  {
    id: "mtk-barisan-arit",
    name: "Barisan Aritmetika",
    latex: "U_n = a + (n-1) b",
    description: "Suku ke-n barisan aritmetika dengan beda b.",
    subject: "matematika",
    topic: "Barisan & Deret",
    variables: [
      { sym: "a", meaning: "suku pertama U₁" },
      { sym: "b", meaning: "beda (Uₙ − Uₙ₋₁)" },
    ],
    tags: ["barisan", "aritmetika"],
  },
  {
    id: "mtk-deret-arit",
    name: "Deret Aritmetika",
    latex: "S_n = \\frac{n}{2}\\bigl(2a + (n-1)b\\bigr)",
    description: "Jumlah n suku pertama deret aritmetika.",
    subject: "matematika",
    topic: "Barisan & Deret",
    tags: ["deret", "aritmetika"],
  },
  {
    id: "mtk-barisan-geo",
    name: "Barisan Geometri",
    latex: "U_n = a \\, r^{\\,n-1}",
    description: "Suku ke-n barisan geometri dengan rasio r.",
    subject: "matematika",
    topic: "Barisan & Deret",
    tags: ["barisan", "geometri"],
  },
  {
    id: "mtk-deret-geo-takhingga",
    name: "Deret Geometri Tak Hingga",
    latex: "S_\\infty = \\frac{a}{1-r}, \\quad |r| < 1",
    description: "Jumlah tak hingga deret geometri konvergen.",
    subject: "matematika",
    topic: "Barisan & Deret",
    tips: "Hanya berlaku bila |r| < 1; jika |r| ≥ 1 deret divergen.",
    tags: ["deret", "geometri", "tak hingga"],
  },
  {
    id: "mtk-perbandingan-senilai",
    name: "Perbandingan Senilai",
    latex: "\\frac{a_1}{b_1} = \\frac{a_2}{b_2}",
    description: "Dua besaran naik/turun bersamaan.",
    subject: "matematika",
    topic: "Perbandingan",
    tips: "Kalau satu naik → yang lain naik → senilai (kali silang).",
    tags: ["perbandingan", "senilai"],
  },
  {
    id: "mtk-perbandingan-berbalik",
    name: "Perbandingan Berbalik Nilai",
    latex: "a_1 \\cdot b_1 = a_2 \\cdot b_2",
    description: "Dua besaran berbanding terbalik (satu naik, satu turun).",
    subject: "matematika",
    topic: "Perbandingan",
    tips: "Contoh klasik: jumlah pekerja vs waktu pengerjaan.",
    tags: ["perbandingan", "berbalik"],
  },
  {
    id: "mtk-pythagoras",
    name: "Teorema Pythagoras",
    latex: "c^2 = a^2 + b^2",
    description: "Sisi miring segitiga siku-siku.",
    subject: "matematika",
    topic: "Geometri",
    tags: ["pythagoras", "segitiga"],
  },
  {
    id: "mtk-lingkaran",
    name: "Luas & Keliling Lingkaran",
    latex: "L = \\pi r^2, \\quad K = 2\\pi r",
    description: "Luas dan keliling lingkaran berjari-jari r.",
    subject: "matematika",
    topic: "Geometri",
    tags: ["lingkaran", "luas", "keliling"],
  },
  {
    id: "mtk-rata-rata",
    name: "Rata-rata (Mean)",
    latex: "\\bar{x} = \\frac{\\sum x_i}{n}",
    description: "Rata-rata dari n data.",
    subject: "matematika",
    topic: "Statistika",
    tags: ["statistika", "mean"],
  },
  {
    id: "mtk-peluang",
    name: "Peluang Kejadian",
    latex: "P(A) = \\frac{n(A)}{n(S)}",
    description: "Peluang kejadian A dari ruang sampel S.",
    subject: "matematika",
    topic: "Peluang",
    tags: ["peluang"],
  },
  {
    id: "mtk-kombinasi",
    name: "Kombinasi",
    latex: "C(n,r) = \\binom{n}{r} = \\frac{n!}{r!\\,(n-r)!}",
    description: "Banyak cara memilih r dari n (tanpa urutan).",
    subject: "matematika",
    topic: "Peluang",
    tags: ["kombinasi", "permutasi"],
  },
  {
    id: "mtk-permutasi",
    name: "Permutasi",
    latex: "P(n,r) = \\frac{n!}{(n-r)!}",
    description: "Banyak cara menyusun r dari n (dengan urutan).",
    subject: "matematika",
    topic: "Peluang",
    tips: "Kalau urutan penting → permutasi. Kalau tidak → kombinasi.",
    tags: ["permutasi"],
  },

  /* ============================== FISIKA ============================== */
  {
    id: "fis-kecepatan",
    name: "Kecepatan",
    latex: "v = \\frac{s}{t}",
    description: "Kecepatan rata-rata dari jarak s dalam waktu t.",
    subject: "fisika",
    topic: "Kinematika",
    tags: ["kecepatan", "kinematika"],
  },
  {
    id: "fis-percepatan",
    name: "Percepatan",
    latex: "a = \\frac{\\Delta v}{\\Delta t}",
    description: "Perubahan kecepatan per satuan waktu.",
    subject: "fisika",
    topic: "Kinematika",
    tags: ["percepatan"],
  },
  {
    id: "fis-glbb-1",
    name: "GLBB — Kecepatan",
    latex: "v_t = v_0 + a t",
    description: "Kecepatan setelah waktu t pada GLBB.",
    subject: "fisika",
    topic: "Kinematika",
    tags: ["glbb", "kinematika"],
  },
  {
    id: "fis-glbb-2",
    name: "GLBB — Jarak",
    latex: "s = v_0 t + \\tfrac{1}{2} a t^2",
    description: "Jarak tempuh pada GLBB.",
    subject: "fisika",
    topic: "Kinematika",
    tags: ["glbb", "jarak"],
  },
  {
    id: "fis-glbb-3",
    name: "GLBB — Tanpa Waktu",
    latex: "v_t^2 = v_0^2 + 2 a s",
    description: "Hubungan kecepatan & jarak saat waktu tidak diketahui.",
    subject: "fisika",
    topic: "Kinematika",
    tags: ["glbb"],
  },
  {
    id: "fis-newton-2",
    name: "Hukum Newton II",
    latex: "F = m a",
    description: "Gaya netto = massa × percepatan.",
    subject: "fisika",
    topic: "Dinamika",
    tags: ["newton", "gaya"],
  },
  {
    id: "fis-berat",
    name: "Berat Benda",
    latex: "w = m g",
    description: "Gaya berat dengan percepatan gravitasi g ≈ 9,8 m/s².",
    subject: "fisika",
    topic: "Dinamika",
    tags: ["berat", "gravitasi"],
  },
  {
    id: "fis-gesek",
    name: "Gaya Gesek",
    latex: "f = \\mu \\, N",
    description: "Gaya gesek antara dua permukaan.",
    subject: "fisika",
    topic: "Dinamika",
    tips: "μs (statis) ≥ μk (kinetis). Saat bergerak, pakai μk.",
    tags: ["gesek", "gaya"],
  },
  {
    id: "fis-usaha",
    name: "Usaha",
    latex: "W = F \\, s \\cos\\theta",
    description: "Usaha oleh gaya F yang membentuk sudut θ terhadap perpindahan.",
    subject: "fisika",
    topic: "Usaha & Energi",
    tags: ["usaha"],
  },
  {
    id: "fis-energi-kinetik",
    name: "Energi Kinetik",
    latex: "E_k = \\tfrac{1}{2} m v^2",
    description: "Energi gerak benda bermassa m berkecepatan v.",
    subject: "fisika",
    topic: "Usaha & Energi",
    tags: ["energi", "kinetik"],
  },
  {
    id: "fis-energi-potensial",
    name: "Energi Potensial",
    latex: "E_p = m g h",
    description: "Energi potensial gravitasi pada ketinggian h.",
    subject: "fisika",
    topic: "Usaha & Energi",
    tags: ["energi", "potensial"],
  },
  {
    id: "fis-momentum",
    name: "Momentum",
    latex: "p = m v",
    description: "Momentum linear benda.",
    subject: "fisika",
    topic: "Momentum & Impuls",
    tags: ["momentum"],
  },
  {
    id: "fis-impuls",
    name: "Impuls",
    latex: "I = F \\, \\Delta t = \\Delta p",
    description: "Impuls = perubahan momentum.",
    subject: "fisika",
    topic: "Momentum & Impuls",
    tags: ["impuls"],
  },
  {
    id: "fis-tekanan",
    name: "Tekanan",
    latex: "P = \\frac{F}{A}",
    description: "Tekanan = gaya per satuan luas.",
    subject: "fisika",
    topic: "Fluida",
    tags: ["tekanan", "fluida"],
  },
  {
    id: "fis-hidrostatis",
    name: "Tekanan Hidrostatis",
    latex: "P = \\rho g h",
    description: "Tekanan zat cair pada kedalaman h.",
    subject: "fisika",
    topic: "Fluida",
    tags: ["hidrostatis"],
  },
  {
    id: "fis-archimedes",
    name: "Gaya Archimedes",
    latex: "F_a = \\rho \\, g \\, V",
    description: "Gaya apung pada benda yang tercelup.",
    subject: "fisika",
    topic: "Fluida",
    tags: ["archimedes", "apung"],
  },
  {
    id: "fis-kalor",
    name: "Kalor (Perubahan Suhu)",
    latex: "Q = m \\, c \\, \\Delta T",
    description: "Kalor untuk mengubah suhu benda.",
    subject: "fisika",
    topic: "Suhu & Kalor",
    tags: ["kalor", "suhu"],
  },
  {
    id: "fis-kalor-lebur",
    name: "Kalor Lebur / Uap",
    latex: "Q = m \\, L",
    description: "Kalor untuk perubahan wujud (tanpa perubahan suhu).",
    subject: "fisika",
    topic: "Suhu & Kalor",
    tags: ["kalor", "lebur"],
  },
  {
    id: "fis-ohm",
    name: "Hukum Ohm",
    latex: "V = I \\, R",
    description: "Tegangan = arus × hambatan.",
    subject: "fisika",
    topic: "Listrik",
    tags: ["ohm", "listrik"],
  },
  {
    id: "fis-daya-listrik",
    name: "Daya Listrik",
    latex: "P = V I = I^2 R = \\frac{V^2}{R}",
    description: "Daya disipasi pada komponen listrik.",
    subject: "fisika",
    topic: "Listrik",
    tags: ["daya", "listrik"],
  },
  {
    id: "fis-gelombang",
    name: "Cepat Rambat Gelombang",
    latex: "v = \\lambda f",
    description: "Kecepatan gelombang dari panjang gelombang & frekuensi.",
    subject: "fisika",
    topic: "Gelombang",
    tags: ["gelombang"],
  },
  {
    id: "fis-lensa",
    name: "Rumus Lensa / Cermin",
    latex: "\\frac{1}{f} = \\frac{1}{s} + \\frac{1}{s'}",
    description: "Hubungan fokus, jarak benda, dan jarak bayangan.",
    subject: "fisika",
    topic: "Optik",
    tips: "Perbesaran: M = |s'/s| = |h'/h|.",
    tags: ["lensa", "cermin", "optik"],
  },

  /* =============================== KIMIA ============================== */
  {
    id: "kim-mol-massa",
    name: "Mol dari Massa",
    latex: "n = \\frac{m}{M_r}",
    description: "Jumlah mol dari massa zat dan massa molar.",
    subject: "kimia",
    topic: "Stoikiometri",
    tags: ["mol", "stoikiometri"],
  },
  {
    id: "kim-jumlah-partikel",
    name: "Jumlah Partikel",
    latex: "N = n \\cdot N_A",
    description: "Jumlah partikel = mol × bilangan Avogadro (6,022×10²³).",
    subject: "kimia",
    topic: "Stoikiometri",
    tags: ["avogadro", "partikel"],
  },
  {
    id: "kim-volume-stp",
    name: "Volume Gas (STP)",
    latex: "V = n \\cdot 22{,}4 \\text{ L}",
    description: "Volume gas pada kondisi standar (0 °C, 1 atm).",
    subject: "kimia",
    topic: "Stoikiometri",
    tags: ["stp", "volume"],
  },
  {
    id: "kim-gas-ideal",
    name: "Persamaan Gas Ideal",
    latex: "P V = n R T",
    description: "Hubungan tekanan, volume, mol, dan suhu gas ideal.",
    subject: "kimia",
    topic: "Gas",
    variables: [
      { sym: "R", meaning: "0,082 L·atm/(mol·K)" },
      { sym: "T", meaning: "suhu (Kelvin)" },
    ],
    tags: ["gas", "ideal"],
  },
  {
    id: "kim-molaritas",
    name: "Molaritas",
    latex: "M = \\frac{n}{V}",
    description: "Konsentrasi larutan dalam mol per liter.",
    subject: "kimia",
    topic: "Larutan",
    tags: ["molaritas", "konsentrasi"],
  },
  {
    id: "kim-pengenceran",
    name: "Pengenceran",
    latex: "M_1 V_1 = M_2 V_2",
    description: "Menghitung konsentrasi setelah pengenceran.",
    subject: "kimia",
    topic: "Larutan",
    tags: ["pengenceran"],
  },
  {
    id: "kim-ph",
    name: "pH Larutan",
    latex: "\\text{pH} = -\\log[H^+]",
    description: "Tingkat keasaman larutan.",
    subject: "kimia",
    topic: "Asam-Basa",
    tips: "pH + pOH = 14 (pada 25 °C).",
    tags: ["ph", "asam", "basa"],
  },

  /* ============================== BIOLOGI ============================= */
  {
    id: "bio-fotosintesis",
    name: "Reaksi Fotosintesis",
    latex: "6CO_2 + 6H_2O \\xrightarrow{cahaya} C_6H_{12}O_6 + 6O_2",
    description: "Reaksi pembentukan glukosa pada tumbuhan hijau.",
    subject: "biologi",
    topic: "Metabolisme",
    tags: ["fotosintesis", "klorofil"],
  },
  {
    id: "bio-respirasi",
    name: "Respirasi Aerob",
    latex: "C_6H_{12}O_6 + 6O_2 \\to 6CO_2 + 6H_2O + \\text{energi}",
    description: "Pemecahan glukosa untuk menghasilkan energi (ATP).",
    subject: "biologi",
    topic: "Metabolisme",
    tags: ["respirasi", "atp"],
  },
  {
    id: "bio-pertumbuhan",
    name: "Pertumbuhan Populasi Eksponensial",
    latex: "N_t = N_0 \\cdot 2^{\\,n}",
    description: "Pertumbuhan populasi yang berlipat setiap generasi.",
    subject: "biologi",
    topic: "Populasi",
    tags: ["populasi", "pertumbuhan"],
  },
  {
    id: "bio-hardy-weinberg",
    name: "Hukum Hardy-Weinberg",
    latex: "p^2 + 2pq + q^2 = 1",
    description: "Kesetimbangan frekuensi alel dalam populasi ideal.",
    subject: "biologi",
    topic: "Genetika",
    variables: [
      { sym: "p", meaning: "frekuensi alel dominan" },
      { sym: "q", meaning: "frekuensi alel resesif, p + q = 1" },
    ],
    tags: ["genetika", "alel"],
  },
  {
    id: "bio-mendel",
    name: "Rasio Mendel",
    latex: "\\text{Monohibrid } 3:1, \\quad \\text{Dihibrid } 9:3:3:1",
    description: "Rasio fenotip F₂ pada persilangan Mendel.",
    subject: "biologi",
    topic: "Genetika",
    tags: ["mendel", "persilangan"],
  },
];

/** Daftar tag unik untuk suggestion / filter lanjutan. */
export const FORMULA_ALL_TAGS: string[] = Array.from(
  new Set(FORMULA_LIBRARY.flatMap((f) => f.tags ?? [])),
).sort();