/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStemRouteImport } from './routes/_authenticated/stem'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as AuthenticatedStemIndexRouteImport } from './routes/_authenticated/stem.index'
import { Route as AuthenticatedStemBookmarksRouteImport } from './routes/_authenticated/stem.bookmarks'
import { Route as AuthenticatedStemAnalyticsRouteImport } from './routes/_authenticated/stem.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStemRoute = AuthenticatedStemRouteImport.update({
  id: '/stem',
  path: '/stem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStemIndexRoute = AuthenticatedStemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStemRoute,
} as any)
const AuthenticatedStemBookmarksRoute =
  AuthenticatedStemBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => AuthenticatedStemRoute,
  } as any)
const AuthenticatedStemAnalyticsRoute =
  AuthenticatedStemAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedStemRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/stem': typeof AuthenticatedStemRouteWithChildren
  '/stem/analytics': typeof AuthenticatedStemAnalyticsRoute
  '/stem/bookmarks': typeof AuthenticatedStemBookmarksRoute
  '/stem/': typeof AuthenticatedStemIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/': typeof AuthenticatedIndexRoute
  '/stem/analytics': typeof AuthenticatedStemAnalyticsRoute
  '/stem/bookmarks': typeof AuthenticatedStemBookmarksRoute
  '/stem': typeof AuthenticatedStemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/guide': typeof AuthenticatedGuideRoute
  '/_authenticated/stem': typeof AuthenticatedStemRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/stem/analytics': typeof AuthenticatedStemAnalyticsRoute
  '/_authenticated/stem/bookmarks': typeof AuthenticatedStemBookmarksRoute
  '/_authenticated/stem/': typeof AuthenticatedStemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/guide'
    | '/stem'
    | '/stem/analytics'
    | '/stem/bookmarks'
    | '/stem/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/guide' | '/' | '/stem/analytics' | '/stem/bookmarks' | '/stem'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/guide'
    | '/_authenticated/stem'
    | '/_authenticated/'
    | '/_authenticated/stem/analytics'
    | '/_authenticated/stem/bookmarks'
    | '/_authenticated/stem/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stem': {
      id: '/_authenticated/stem'
      path: '/stem'
      fullPath: '/stem'
      preLoaderRoute: typeof AuthenticatedStemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stem/': {
      id: '/_authenticated/stem/'
      path: '/'
      fullPath: '/stem/'
      preLoaderRoute: typeof AuthenticatedStemIndexRouteImport
      parentRoute: typeof AuthenticatedStemRoute
    }
    '/_authenticated/stem/bookmarks': {
      id: '/_authenticated/stem/bookmarks'
      path: '/bookmarks'
      fullPath: '/stem/bookmarks'
      preLoaderRoute: typeof AuthenticatedStemBookmarksRouteImport
      parentRoute: typeof AuthenticatedStemRoute
    }
    '/_authenticated/stem/analytics': {
      id: '/_authenticated/stem/analytics'
      path: '/analytics'
      fullPath: '/stem/analytics'
      preLoaderRoute: typeof AuthenticatedStemAnalyticsRouteImport
      parentRoute: typeof AuthenticatedStemRoute
    }
  }
}

interface AuthenticatedStemRouteChildren {
  AuthenticatedStemAnalyticsRoute: typeof AuthenticatedStemAnalyticsRoute
  AuthenticatedStemBookmarksRoute: typeof AuthenticatedStemBookmarksRoute
  AuthenticatedStemIndexRoute: typeof AuthenticatedStemIndexRoute
}

const AuthenticatedStemRouteChildren: AuthenticatedStemRouteChildren = {
  AuthenticatedStemAnalyticsRoute: AuthenticatedStemAnalyticsRoute,
  AuthenticatedStemBookmarksRoute: AuthenticatedStemBookmarksRoute,
  AuthenticatedStemIndexRoute: AuthenticatedStemIndexRoute,
}

const AuthenticatedStemRouteWithChildren =
  AuthenticatedStemRoute._addFileChildren(AuthenticatedStemRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRoute
  AuthenticatedStemRoute: typeof AuthenticatedStemRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGuideRoute: AuthenticatedGuideRoute,
  AuthenticatedStemRoute: AuthenticatedStemRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
